---
queues:
  Lims-CF:
    driver: Courier
    options:
      dsn: tcp://192.168.0.5:7333
      queue: Lims-CF
  YiQiKong:
    driver: Courier
    options:
      dsn: tcp://192.168.0.5:7333
      queue: YiQiKong
...
