---
queues:
  Lims-CF:
    driver: Courier
    options:
      dsn: tcp://debade-courier.docker.local:3333
      queue: Lims-CF
  YiQiKong:
    driver: Courier
    options:
      dsn: tcp://debade-courier.docker.local:3333
      queue: YiQiKong
...